import { Link } from 'react-router-dom'
import { characters, ctas } from '../data/content'
import { Hero } from '../components/Hero'
import { CharacterCard } from '../components/Cards'
import { SectionHeader } from '../components/SectionHeader'
import { CTASection } from '../components/Sections'
import { Card } from '../components/ui/card'
import { Button } from '../components/ui/button'
import { SEO } from '../components/SEO'

export function HearteFamily() {
  return <><SEO title="Meet The Hearte Family" /><Hero compact eyebrow="Meet the Hearte Family" title="Everyday family moments become emotional language children can use." primary={ctas.hearteTools}><p>The Hearte Family introduces younger children to emotional language, family connection, kindness, confidence, repair, and everyday problem-solving.</p></Hero><section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeader title="Character cards with SEL focus" eyebrow="Canon family" /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{characters.map((character) => <CharacterCard key={character.name} character={character} />)}</div></div></section><section className="bg-white/55 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeader title="Book and product preview pathways" eyebrow="Story tools" /><div className="mt-10 grid gap-5 md:grid-cols-3"><Preview title="Story picture books" text="Short, warm scenarios for naming feelings, practicing repair, and connecting as a family." /><Preview title="Printable home kits" text="Feelings charts, calm-down cards, conversation starters, and reflection prompts." /><Preview title="Classroom mini-lessons" text="Educator-ready prompts that turn Hearte Family moments into discussion and practice." /></div><div className="mt-8"><Button asChild><Link to="/resources">Explore The Hearte Family SEL Tools</Link></Button></div></div></section><section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeader title="How grown-ups can use The Hearte Family" eyebrow="Use cases" /><div className="mt-10 grid gap-5 md:grid-cols-2"><Card><h3 className="font-heading text-2xl text-plum">Parents and caregivers</h3><p className="mt-3 leading-7 text-ink/75">Use stories before bed, after school, or during conflict repair to help children name feelings without shame and choose one safe next step.</p></Card><Card><h3 className="font-heading text-2xl text-plum">Educators and counselors</h3><p className="mt-3 leading-7 text-ink/75">Introduce a character moment as a low-pressure way to discuss kindness, confidence, listening, repair, and asking for help.</p></Card></div></div></section><CTASection title="Bring The Hearte Family into your SEL routine." primary={ctas.hearteTools} secondary={{ label: 'Request educator preview', href: '/contact-partner' }} /></>
}
function Preview({ title, text }) { return <Card><h3 className="font-heading text-2xl text-plum">{title}</h3><p className="mt-3 leading-7 text-ink/75">{text}</p></Card> }
