import { adventures } from '../data/content'
import { Hero } from '../components/Hero'
import { AdventureCard } from '../components/Cards'
import { SectionHeader } from '../components/SectionHeader'
import { CTASection } from '../components/Sections'
import { Card } from '../components/ui/card'
import { SEO } from '../components/SEO'

export function Wonderhood() {
  return <><SEO title="The Wonderhood Adventures" /><Hero compact eyebrow="The Wonderhood Adventures" title="A story-driven world for friendship, courage, repair, and curious problem-solving." primary={{ label: 'Start with the map', href: '/app-experience' }} secondary={{ label: 'View curriculum links', href: '/sel-curriculum' }}><p>The Wonderhood Adventures is a story-driven SEL and problem-solving world where children ages 7–12 learn emotional intelligence, friendship, repair, cultural respect, curiosity, and courage through adventure.</p></Hero><section className="py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeader eyebrow="Core world" title="ImagiNation Street connects SEL, STEAM, cultural intelligence, and teamwork."><p>Children explore Heritage House, ensemble-cast stories, and adventure destinations with no single lead — every child can find a way into the world.</p></SectionHeader><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><Card><h3 className="font-heading text-xl text-plum">ImagiNation Street</h3><p className="mt-2 text-ink/75">The welcoming neighborhood where adventures begin.</p></Card><Card><h3 className="font-heading text-xl text-plum">Heritage House</h3><p className="mt-2 text-ink/75">A gathering place for stories, traditions, and belonging.</p></Card><Card><h3 className="font-heading text-xl text-plum">Ensemble cast</h3><p className="mt-2 text-ink/75">No single lead; teamwork and multiple perspectives matter.</p></Card><Card><h3 className="font-heading text-xl text-plum">SEL + STEAM</h3><p className="mt-2 text-ink/75">Curiosity, creativity, and practical problem-solving.</p></Card></div></div></section><section className="bg-white/55 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeader title="Adventure cards" eyebrow="Choose a path" /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{adventures.map((adventure) => <AdventureCard key={adventure.title} adventure={adventure} />)}</div></div></section><CTASection title="Let Wonderhood become your child-safe SEL adventure layer." primary={{ label: 'Explore app experience', href: '/app-experience' }} secondary={{ label: 'Partner with LYF4Kids', href: '/contact-partner' }} /></>
}
